### ISSUE TITLE
در خواست افزودن فایل TODO به مخزن 

### ISSUE THREAD

**Issue by KomeilParseh** [mehrdad-dev/scikit-learn#2]
<div dir="rtl">
سلام خسته نباشید مخزن خیلی دردم خورد ممنون از ولی بهتره که برای بهتر شدن همکاری ها و نشان دادن پیشرفت مخزن پیشنهاد میکنم که قسمت TODO های مخزن رو ایجاد کنید. البته خودتون از من واردترین توضیح بیشتر نمی‌دم.

موفق باشید:)
</div>

**Comment by mehrdad-dev** [comment]
سلام روز بخیر
[اینجا](https://github.com/mehrdad-dev/scikit-learn/wiki/%D9%85%D8%B4%D8%A7%D8%B1%DA%A9%D8%AA#%D8%A7%D9%84%D9%88%DB%8C%D8%AA-%D9%87%D8%A7%DB%8C-%D9%85%D8%B4%D8%A7%D8%B1%DA%A9%D8%AA)
و
[اینجا](https://sklearn.ir/translate/)
الویت های کاری رو معلوم کردیم ولی باشه حتما داخل فایل readme هم وارد می‌کنیم.

**Comment by KomeilParseh** [comment]
سلام ممنون بله دیدم اینا رو منظور من اینه که نوشته بشه کدام فصل یا قسمت داره ترجمه میشه یا در آینده ترجمه میشه هستش

**Comment by mehrdad-dev** [comment]
داخل قسمت `مشاهده روند ترجمه` به صورت کلی گفته شده که الان در چه وضعیتی هست،
و برای دوستانی که قصد همکاری دارند گفتیم یک ایشو باز کنن تا با هم دقیق هماهنگ کنیم کدوم قسمت ها.

**Comment by KomeilParseh** [comment]
بسیار متشکر

**Comment by KomeilParseh** [comment]
بسیار متشکر :)
